version: '2'
services:
  client:
    build: ./nodejs
    container_name: csg-client
    restart: always
    working_dir: "/src"
    ports:
      - "8150:3000"
    volumes:
      - "./kindai-csg.dev:/src"
    tty: true